//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelAPP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Account
    {
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> userID { get; set; }
        public virtual Employee Employee { get; set; }

        protected HotelDB hotelDB;
        public Account()
        {
            hotelDB = new HotelDB();
        }
        public bool getLogin(string username, string password)
        {
            try
            {
                var accounts = (from a in hotelDB.Accounts
                                join e in hotelDB.Employees on a.userID equals e.Id
                                join p in hotelDB.Positions on e.posId equals p.posId
                                where a.username == username && a.password == password
                                select new
                                {
                                    Username = a.username,
                                    Id = e.Id,
                                    PosId = e.posId,
                                    PosName = p.posName,
                                    Avatar = e.avatar
                                }).ToArray();
                if (accounts.Length < 0)
                {
                    return false;
                }
                else
                {
                    CurrentUser.UserName = accounts[0].Username;
                    CurrentUser.Id = accounts[0].Id;
                    CurrentUser.PositionNum = accounts[0].PosId.Value;
                    CurrentUser.PositionName = accounts[0].PosName;
                    if (accounts[0].Avatar != null)
                    {
                        CurrentUser.Avatar = new HotelAPP.Tools.ImageTool().ByteArrToImage(accounts[0].Avatar);
                    }
                    return true;
                }
            }
            catch (Exception)
            {
                return false;
            }
        }
        public bool ExistUsernamCheck(string username)
        {
            try
            {
                var listUsername = (from a in hotelDB.Accounts
                                    where a.username == username
                                    select a.username).ToArray();
                if (listUsername.Length == 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception)
            {
                return false;
            }
        }
        //public bool AddNewGuestAccount(string username, string password)
        //{
        //    try
        //    {
        //        if (ExistUsernamCheck(username) == false) return false;

        //        Account account = new Account()
        //        {
        //            username = username,
        //            password = password
        //        };
        //        hotelDB.Accounts.Add(account);
        //        hotelDB.SaveChanges();
        //        return true;
        //    }
        //    catch (Exception)
        //    {
        //        return false;
        //    }
        //}
    }
}
