//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consume
    {
        public int id { get; set; }
        public Nullable<int> roomID { get; set; }
        public string roomName { get; set; }
        public Nullable<int> productID { get; set; }
        public string productName { get; set; }
        public Nullable<int> consume1 { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Room Room { get; set; }
    }
}
